on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls
  job2:
    runs-on: windows-latest
    steps:
    - run: pwd
    - uses: actions/checkout@v4
    # - name: Checkout repository code
    #   uses: actions/checkout@v2
    # - name: Setup Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '16.16.0'
    - name: install modules
      run: npm install
    - name: build on
      run: npm run build 
      # working-directory: frontend
